name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  # 🔹 Job 1: integración básica
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: "1"
        run: npm run build

  # 🔹 Job 2: seguridad básica
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Audit
        run: npm audit --production --audit-level=moderate || true

      - name: Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: HEAD
